### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PushkarOP** [David-pm-pl/MPCScoreTag#1]
Error: Class "davidglitch04\MultiPlayerCounter\Event\PlayerMergedEvent" does not exist
File: pmsrc/src/plugin/PluginManager
Line: 522
Type: ReflectionException

**Comment by DaDevGuy** [comment]
Pushkar Spotted

**Comment by PushkarOP** [comment]
Pushkar always everywhere

**Comment by DavidGlitch04** [comment]
Please use MultiPlayerCounter [v0.0.4](https://github.com/David-pm-pl/MultiPlayerCounter/releases/tag/v0.0.4)

**Comment by DaDevGuy** [comment]
> Pushkar always everywhere

lol
